config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/dashboard', to: "pages#dashboard"
  get '/dashboard/edit', to: "pages#dashboard_edit"
  patch '/dashboard/edit', to: "pages#dashboard_update"


  get 'diggers/search', to: 'diggers#search'
  get 'diggers/mine', to: 'diggers#mine'

  get 'bookings/mine', to: 'bookings#mine'
  get '/bookings/requests_received', to: 'bookings#received', as: 'bookings_received'
  get 'bookings/:id/approval/:boolean', to: 'bookings#approval'

  resources :diggers do
    resources :bookings
  end

  resources :conversations do
    resources :messages
  end

  resources :channels, only: [:show, :index, :create] do
    resources :letters, only: [:create]
  end

  mount ActionCable.server => "/cable"

end

app/views/shared/_featured_card.html.erb
<div class=".card-container-featured-digger col-6 col-lg-4">
  <%= link_to digger_path(digger) do  %>
  <div class="card-featured-digger">
    <%= cl_image_tag digger.photo, height: 400, width: 400 %>
    <div class="card-featured-digger-infos text-center">
      <h2 id="title"><%= digger.name %></h2>
      <p id="subdata"><%= digger.day_rate %>€ per day</p>
    </div>
  </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/maxwrf/dig-it"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <span class="thematic-blur">I dig therefore I am.</div> © Can I Dig It International, 2019.
  </span>
</div>

app/views/shared/_matched_digger_card.erb
<div class="card-product digger" data-aos="fade-in">
  <%= cl_image_tag digger.photo, height: 300, width: 400, crop: :fill %>
  <div class="digger-name">
    <p><%= digger.name %></p>
  </div>
  <div class="tech-spec">
    <p><%= digger.technical_specification %></p>
  </div>
  <div class="cost-per-day">
    <p><%= digger.day_rate %>€</p>
    <p class="col-text-secondary">per day</p>
  </div>
  <div class="buttons">
  <% if (current_user == digger.user) && !digger.bookings.empty? %>
  <p class="btn btn-sm btn-primary"><%= link_to "Requests", digger_bookings_path(digger) %></p>
  <% end %>
  <% if current_user != digger.user %>
  <p class="btn btn-sm btn-primary"><%= link_to "View", digger_path(digger) %></p>
  <% end %>
   <% if policy(digger).edit? %>
   <p class="btn btn-sm btn-info"><%= link_to "Edit ⚙️", edit_digger_path(digger) %></p>
   <% end %>
   <% if policy(digger).destroy? %>
      <p class="btn btn-sm btn-danger"><%= link_to "Delete ✂️", digger_path(digger), method: :delete %></p>
    <% end %>
 </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-all">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Fimage.flaticon.com%2Ficons%2Fpng%2F512%2F46%2F46818.png&f=1" %>
    <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item mt-1">
          <%= form_tag diggers_path, :method => :get do %>
          <%= text_field_tag(:search, params[:search], :class => "banner-typed-text", :id => "search_field", placeholder: "Search for a digger!") %>
          <%= submit_tag "Search", :name => nil %>
          <% end %>
        </li>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Channels", channels_path, class: "nav-link" %>
        </li>

        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.photo, height: 40, width: 40, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Messages", conversations_path, class: "dropdown-item" %>
            <%= link_to "My diggers", diggers_mine_path, class: "dropdown-item" %>
            <%= link_to "Add digger", new_digger_path, class: "dropdown-item" %>
            <div class="dropdown-item">
              <%= link_to "All bookings", bookings_mine_path, class: "text-color-black" %>
              <% if @approved_bookings > 0 %>
                <span class="badge badge-danger"><%= @approved_bookings %></span>
                <span class="sr-only">unread messages</span>
              <% end %>
            </div>
            <div class="dropdown-item">
              <%= link_to "Requests received", bookings_received_path , class: "text-color-black" %>
              <% if  @out_req_renter > 0 %>
                <span class="badge badge-danger"><%= @out_req_renter %></span>
                <span class="sr-only">unread messages</span>
              <% end %>
            </div>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_requested_digger_card.erb
<div class="card-product request" data-aos="fade-in">
  <%= cl_image_tag booking.digger.photo, height: 300, width: 400, crop: :fill %>
  <div class="first">
    <p class="request-title">Request for:</p>
    <p class="digger-name"><%= booking.digger.name %></p>
  </div>
  <div>
    <% if variant == 'req_made' %>
    <p class="request-title">Owner:</p>
    <p class="renter-name"><%= booking.digger.user.full_name %></p
    <% else %>
    <p class="request-title">From:</p>
    <p class="renter-name"><%= booking.user.full_name %></p>
    <% end %>
    <% ago = (booking.created_at - DateTime.now)/-3600/24%>
    <% ago = ago.to_f.round %>
    <% if ago > 1 %>
    <% message = "#{ago} days ago" %>
    <% else %>
    <% message = ago == 0 ? "Today" : "Yesterday" %>
    <% end %>
    <p class=""><%= message %></p> <!-- TODO -->
  </div>
  <!-- TODO: once renter profile pages link_to booking.digger.user.full_name, user_path(booking.user) %> -->
  <div>
    <p class="request-title">Dates:</p>
    <p class="dates"><%= booking.start_date %></p>
    <p class="dates"><%= booking.end_date %></p>
    <% request_days = (booking.end_date - booking.start_date).to_i %>
    <% day_string = request_days == 1 ? "day" : "days" %>
    <% string = "#{request_days} #{day_string}" %>
    <p class="">(<%= string %>)</p>
  </div>
  <div>
    <% if booking.approved === true %>
    <p class="btn btn-sm btn-primary "><%= link_to "View",digger_path(booking.digger.id)  %></p> <!-- TODO: only if not begun -->
    <% elsif booking.approved === nil && variant == 'req_received' %>
    <p class="btn btn-sm btn-success "><%= link_to "Accept", "/bookings/#{booking.id}/approval/true", class:"text-white" %></p>
    <p class="btn btn-sm btn-danger"><%= link_to "Reject", "/bookings/#{booking.id}/approval/false", class:"text-white" %></p>
    <!-- TODO: only if not begun -->
    <% else %>
    <p class="btn btn-sm btn-primary "><%= link_to "View",digger_path(booking.digger.id)  %></p>  <!-- TODO: only if not begun -->
    <% end %>
  </div>
</div>