config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/dashboard', to: "pages#dashboard"
  get '/dashboard/edit', to: "pages#dashboard_edit"
  patch '/dashboard/edit', to: "pages#dashboard_update"


  get 'diggers/search', to: 'diggers#search'
  get 'diggers/mine', to: 'diggers#mine'

  get 'bookings/mine', to: 'bookings#mine'
  get '/bookings/requests_received', to: 'bookings#received', as: 'bookings_received'
  get 'bookings/:id/approval/:boolean', to: 'bookings#approval'

  resources :diggers do
    resources :bookings
  end

  resources :conversations do
    resources :messages
  end

  resources :channels, only: [:show, :index, :create] do
    resources :letters, only: [:create]
  end

  mount ActionCable.server => "/cable"

end

app/views/pages/_navbar-home.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Fimage.flaticon.com%2Ficons%2Fpng%2F512%2F46%2F46818.png&f=1" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto navbar-other navbar-hidden">
      <% if user_signed_in? %>
        <li class="nav-item mt-1">
          <%= form_tag diggers_path, :method => :get do %>
          <%= text_field_tag(:search, params[:search], :class => "banner-typed-text", :id => "search_field", placeholder: "Search for a digger!") %>
          <%= submit_tag "Search", :name => nil %>
          <% end %>
        </li>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Channels", channels_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.photo, height: 40, width: 40, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Messages", conversations_path, class: "dropdown-item" %>
            <%= link_to "My diggers", diggers_mine_path, class: "dropdown-item" %>
            <div class="dropdown-item">
              <%= link_to "All bookings", bookings_mine_path, class: "text-color-black" %>
              <% if @approved_bookings > 0 %>
                <span class="badge badge-danger"><%= @approved_bookings %></span>
                <span class="sr-only">unread messages</span>
              <% end %>
            </div>
            <div class="dropdown-item">
              <%= link_to "Requests received", bookings_received_path , class: "text-color-black" %>
              <% if  @out_req_renter > 0 %>
                <span class="badge badge-danger"><%= @out_req_renter %></span>
                <span class="sr-only">unread messages</span>
              <% end %>
            </div>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/pages/_navbar_home.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Fimage.flaticon.com%2Ficons%2Fpng%2F512%2F46%2F46818.png&f=1" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto navbar-other navbar-hidden">
      <% if user_signed_in? %>
        <li class="nav-item mt-1">
          <%= form_tag diggers_path, :method => :get do %>
          <%= text_field_tag(:search, params[:search], :class => "banner-typed-text", :id => "search_field", placeholder: "Search for a digger!") %>
          <%= submit_tag "Search", :name => nil %>
          <% end %>
        </li>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Channels", channels_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.photo, height: 40, width: 40, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Messages", conversations_path, class: "dropdown-item" %>
            <%= link_to "My diggers", diggers_mine_path, class: "dropdown-item" %>
            <%= link_to "Add digger", new_digger_path, class: "dropdown-item" %>
            <div class="dropdown-item">
              <%= link_to "All bookings", bookings_mine_path, class: "text-color-black" %>
              <% if @approved_bookings > 0 %>
                <span class="badge badge-danger"><%= @approved_bookings %></span>
                <span class="sr-only">unread messages</span>
              <% end %>
            </div>
            <div class="dropdown-item">
              <%= link_to "Requests received", bookings_received_path , class: "text-color-black" %>
              <% if  @out_req_renter > 0 %>
                <span class="badge badge-danger"><%= @out_req_renter %></span>
                <span class="sr-only">unread messages</span>
              <% end %>
            </div>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/pages/dashboard.html.erb
<div class="container align-content-center text-center ">
  <h1 class="my-3">Your Profil <%=@user.first_name %>!</h1>
  <div class="card align-items-center text-center m-auto " style="width: 30rem;">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">First name:</li>
      <li class="list-group-item"><%= @user.first_name %></li>
    </ul>
  </div>
  <div class="card align-items-center text-center m-auto" style="width: 30rem;">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Last name:</li>
      <li class="list-group-item"><%= @user.last_name %></li>
    </ul>
  </div>
  <div class="card align-items-center text-center m-auto" style="width: 30rem;">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Your email:</li>
      <li class="list-group-item"><%= @user.email %></li>
    </ul>
  </div>
  <div class="card align-items-center text-center m-auto" style="width: 30rem;">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Password:</li>
      <li class="list-group-item"><%= link_to "Change your password", edit_user_registration_path %></li>
    </ul>
  </div>
  <div class="align-items-center text-center m-3">
    <a class="btn btn-secondary" href="dashboard/edit" role="button">Edit</a>
  </div>
 </div>

app/views/pages/dashboard_edit.html.erb
<div class="container p-4  ">
  <%= simple_form_for(@user, url: dashboard_edit_path)  do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <%= f.input :photo %>
   <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit "Update", class: "btn btn-secondary" %>
  <a class="btn btn-secondary" href="/dashboard" role="button">Back</a>
<% end %>
</div>

app/views/pages/home.html.erb
<div class="banner-home" style="background-image:  linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.1)), url('https://images.unsplash.com/photo-1495036019936-220b29b930ea?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=3300&q=80');">
  <div class="container" id="banner-home">
    <div>
      <h1 class="col-thematic-inv">CAN I DIG IT</h1>
      <br>
      <h3 class="text-white">professional excavating equipment!</h3>
      <p class="text-white">Change your life by digging holes all around the world.</p>
    </div>
  </div>
  <div class="container">
      <div class="date-form text-center mt-5 navbar-trans">
      <h2 class="col-text-primary" style="margin-bottom: 30px;">Book a digger.</h1>
      <%= form_tag diggers_path, :method => :get do %>
      <div class="form-group">
        <%= label_tag(:start_date_day, "Start:") %>
        <%= select_date(Date.today, prefix: :start_date) %>
      </div>
      <div class="form-group">
        <%= label_tag(:end_date_day, "  End:") %>
        <%= select_date(Date.today, prefix: :end_date) %>
      </div>
      <%= submit_tag("Search", class: "btn btn-secondary text-white")%>
      <% end %>
    </div>
</div>
</div>

  <div style="margin-bottom: 50px">
  <h2 class="mb-4 mt-5 text-center">Featured Diggers</h2>
  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner container">
      <div class="carousel-item active">
        <% if @diggers.length >= 3 %>
          <div class=" container d-flex d-block w-100">
            <%= render partial: "shared/featured_card", locals: {digger: @diggers[-4]}%>
            <%= render partial: "shared/featured_card", locals: {digger: @diggers[-5]}%>
            <%= render partial: "shared/featured_card", locals: {digger: @diggers[-6]}%>
          </div>
        <% end %>
      </div>
      <div class="carousel-item">
        <% if @diggers.length >= 6 %>
          <div class=" container d-flex d-block w-100">
            <%= render partial: "shared/featured_card", locals: {digger: @diggers[-7]}%>
            <%= render partial: "shared/featured_card", locals: {digger: @diggers[-8]}%>
            <%= render partial: "shared/featured_card", locals: {digger: @diggers[-9]}%>
          </div>
        <% end %>
      </div>
      <div class="carousel-item">
        <% if @diggers.length >= 9 %>
          <div class=" container d-flex d-block w-100">
            <%= render partial: "shared/featured_card", locals: {digger: @diggers[-1]}%>
            <%= render partial: "shared/featured_card", locals: {digger: @diggers[-2]}%>
            <%= render partial: "shared/featured_card", locals: {digger: @diggers[-3]}%>
          </div>
        <% end %>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <i class="fas fa-chevron-left" style="color: #333333"></i>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <i class="fas fa-chevron-right" style="color: #333333"></i>
      <span class="sr-only">Next</span>
    </a>
  </div>

  <div style="margin-bottom: 50px">
  <h2 class="mb-4 mt-5 text-center">Recently added Diggers</h2>
  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner container">

      <% newest = [@diggers[-1], @diggers[-2], @diggers[-3]] %>

      <div class="carousel-item active">
        <% if newest.length >= 3 %>
          <div class=" container d-flex d-block w-100">
            <%= render partial: "shared/featured_card", locals: {digger: newest[-1]}%>
            <%= render partial: "shared/featured_card", locals: {digger: newest[-2]}%>
            <%= render partial: "shared/featured_card", locals: {digger: newest[-3]}%>
          </div>
        <% end %>
      </div>
  </div>
 </div>